create table "OFFICINAADMIN".VEICOLO
(
	MATRICOLA VARCHAR(10) not null primary key,
	CF_PROPRIETARIO VARCHAR(25),
	TIPO_VEICOLO VARCHAR(15),
	MARCA VARCHAR(15),
	TIPO_CARBURANTE VARCHAR(15),
	CILINDRATA INTEGER,
	STATO_VEICOLO VARCHAR(25),
FOREIGN KEY (CF_PROPRIETARIO) REFERENCES PROPRIETARIO(CF)
)
